### ISSUE TITLE
Browser sources not available.  (Refer to MMdisc from Reddit's version for inspiration to get it working)

### ISSUE THREAD

**Issue by FieryEarth** [carlosonunez/obs-installer-for-apple-silicon#6] opened 2021-06-28 03:20 UTC
MMdisc on Reddit made a version that works with browser sources (as long as HW acceleration on browser capture is disabled)

**Comment by FieryEarth** [comment] 2021-06-28 14:31
the version can be found in this thread:
https://www.reddit.com/r/obs/comments/njwbxl/compiling_obs_for_apple_silicon_m1/h2dw750/?context=3

**Comment by FieryEarth** [comment] 2021-06-29 14:25
For context: MMdisc's version works without HW acceleration on browser capture, which is better than no browser capture. But if HW acceleration for Browser Capture can be solved, then OBS.Ninja would work much better.

**Comment by carlosonunez** [comment] 2021-07-06 19:18
Closing, as this is a duplicate of #8.

**Closed by carlosonunez** 2021-07-06 19:18 UTC
