### ISSUE TITLE
 fatal error: 'mbedtls/arc4.h' file not found

### ISSUE THREAD

**Issue by the-sushi** [carlosonunez/obs-installer-for-apple-silicon#11] opened 2021-07-16 00:42 UTC
When running the installer I get:

```
[ 54%] Building C object plugins/obs-outputs/CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o
In file included from /tmp/obs/plugins/obs-outputs/librtmp/rtmp.c:178:
/tmp/obs/plugins/obs-outputs/librtmp/handshake.h:29:10: fatal error: 'mbedtls/arc4.h' file not found
#include <mbedtls/arc4.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
```

Indeed, ` /opt/homebrew/include/mbedtls` does not include an `arc4.h`, including only the following:

```
aes.h                 ccm.h                 ctr_drbg.h            entropy.h             memory_buffer_alloc.h platform.h            sha1.h                threading.h
aria.h                chacha20.h            debug.h               error.h               net_sockets.h         platform_time.h       sha256.h              timing.h
asn1.h                chachapoly.h          des.h                 gcm.h                 nist_kw.h             platform_util.h       sha512.h              version.h
asn1write.h           check_config.h        dhm.h                 hkdf.h                oid.h                 poly1305.h            ssl.h                 x509.h
base64.h              cipher.h              ecdh.h                hmac_drbg.h           pem.h                 private_access.h      ssl_cache.h           x509_crl.h
bignum.h              cmac.h                ecdsa.h               mbedtls_config.h      pk.h                  psa_util.h            ssl_ciphersuites.h    x509_crt.h
build_info.h          compat-2.x.h          ecjpake.h             md.h                  pkcs12.h              ripemd160.h           ssl_cookie.h          x509_csr.h
camellia.h            config_psa.h          ecp.h                 md5.h                 pkcs5.h               rsa.h                 ssl_ticket.h
```

**Comment by cicloid** [comment] 2021-07-19 22:57
Try the following:

1. Uninstall the latest version and rollback the older version 2 of mbedtls 
```
brew remove mbedtls
brew install mbedtls@2
```

2.  Edit the install.sh and change the `mbedtls` to use `mbedtls@2`, this to avoid the reinstall of the new version.
3. Compile with `REPACKAGE=true ./install.sh`
4. ???
5. Profit!

**Comment by ThomasWaldmann** [comment] 2021-07-28 01:46
@cicloid thanks, I can confirm that your solution works!

**Comment by ThomasWaldmann** [comment] 2021-07-28 01:47
The remaining questions is for what they need crypto as crappy as arc4. :-)

**Comment by tobiasbischoff** [comment] 2021-07-28 11:07
Ran into the same issue, maybe someone should change install.sh to ask for mbedtls@2 in the first place.

**Comment by carlosonunez** [comment] 2021-08-29 20:10
Hello! I just did a fresh rebuild of OBS 27.0.1 and, unfortunately, wasn't able to replicate this issue. However, since I did merge the PR that fixes this, I'm going to close this issue. Feel free to re-open it if this continues to be a problem.

**Closed by carlosonunez** 2021-08-29 20:10 UTC
